# Generated by Django 5.2.5 on 2025-08-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('as_of_date', models.DateField(auto_now_add=True)),
                ('momentum_returns', models.FloatField(default=0.0)),
                ('momentum_score', models.FloatField(default=0.0)),
                ('news_title', models.CharField(blank=True, max_length=255, null=True)),
                ('news_description', models.TextField(blank=True, null=True)),
                ('pulse', models.CharField(blank=True, max_length=255, null=True)),
                ('llm_explanation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
