# Generated by Django 5.2.5 on 2025-08-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='news_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
