# Generated by Django 5.2.5 on 2025-08-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0002_stock_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='as_of_date',
            field=models.DateField(),
        ),
    ]
